server:
  port: 8080
  servlet:
    context-path: /bookstore

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/book_store"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
